# Config file for automatic testing at travis-ci.org

sudo: false
language: python
dist: xenial

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
  - pip install tox-travis

# command to run tests, e.g. python setup.py test
script:
  - tox
