# Config file for automatic testing at travis-ci.org

sudo: required
language: python
dist: xenial

matrix:
  include:
  - python: "3.4"
  - python: "3.5"
  - python: "3.6"
  - python: "3.7"
  - python: "3.8-dev"
    env: TOXENV=py38

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
  - pip install tox-travis

# command to run tests, e.g. python setup.py test
script:
  - tox
