name: Build

on:
  push:
    branches: [main, pre-release]
    tags: ['v*']
  pull_request:
    branches: [main, pre-release]
  workflow_dispatch:
env:
  LATEST_PY_VERSION: '3.9'
  COVERAGE_ARGS: '--cov --cov-report=term --cov-report=html'


jobs:
  # Run unit tests for each supported python version
  test:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9, 3.10.0-beta.1]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: snok/install-poetry@v1.1.6
        with:
          version: 1.2.0a1
          virtualenvs-in-project: true

      # Cache packages per python version, and reuse until lockfile changes
      - name: Cache python packages
        id: cache
        uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ matrix.python-version }}-${{ hashFiles('poetry.lock') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: poetry install -v

      - name: Run unit tests
        run: poetry run pytest -n auto

  # Run code analysis checks, reports, etc.
  analyze:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ env.LATEST_PY_VERSION }}
      - uses: snok/install-poetry@v1.1.6
        with:
          version: 1.2.0a1
          virtualenvs-in-project: true

      # Cache packages and reuse until lockfile changes
      - name: Cache python packages
        id: cache
        uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ env.LATEST_PY_VERSION }}-${{ hashFiles('poetry.lock') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: poetry install -v

      - name: Run style checks, type checks, and linting
        run: |
          source $VENV
          black --check --diff .
          isort --check --diff .
          flake8 .
          mypy pyinaturalist
      - name: Generate and send code coverage report to Coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          source $VENV
          pytest -n auto ${{ env.COVERAGE_ARGS }}
          pip install coveralls
          coveralls --service=github

  # Deploy pre-release builds from 'pre-release' branch, and stable builds on tags only
  release:
    needs: [test, analyze]
    if: startsWith(github.ref, 'refs/tags/v') || endsWith(github.ref, '/pre-release')
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ env.LATEST_PY_VERSION }}
      - uses: snok/install-poetry@v1.1.6
        with:
          version: 1.2.0a1
          virtualenvs-in-project: true

      - name: Set pre-release version number
        if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        run: poetry version $(poetry version -s).dev${GITHUB_RUN_NUMBER}
      - name: Build and publish to pypi
        run: |
          poetry build
          poetry publish -u __token__ -p ${{ secrets.PYPI_TOKEN }}

      # Notify Docker image repo that there's a new release available
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.DOCKERHUB_TRIGGER_TOKEN }}
          repository: JWCook/inaturalist-notebook
          event-type: post-release
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
